module.exports = {
    extends: [
        "config:base",
        ":disableMajorUpdates",
        ":ignoreModulesAndTests",
        ":pinVersions",
        ":rebaseStalePrs",
        ":automergeDigest",
        ":automergePatch",
        ":automergePr",
        ":automergeRequireAllStatusChecks",
        ":automergeLinters",
        ":automergeTesters",
        ":automergeTypes",
        "packages:eslint",
        "workarounds:typesNodeVersioning",
    ],
    branchPrefix: "renovate/",
    platform: "github",
    repositories: ["RecruitWizard/JobsWidget"],
    packageRules: [],
    rebaseWhen: "conflicted",
    timezone: "Australia/Sydney",
    onboarding: false,
    requireConfig: false,
};
