name: Build & Test

on:
  push:
    branches:    
      - '**' # matches every branch
    paths: 
          - "**"    
          - "!.octopus/**"      
  workflow_dispatch:      
  release:
    types: [created] 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: '5.x'
        
    - name: Display GitVersion config
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.11
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
        additionalArguments: "/updateprojectfiles"
        
    - name: Display GitVersion outputs
      run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"
     
    - name: Build the Docker Image 
      working-directory: src
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_SERVER_URL }}/jobs-widget:${{ steps.gitversion.outputs.fullSemVer }} 
       
    - name: Login to Azure Container Registry 
      uses: docker/login-action@v1  
      with: 
        registry: ${{ secrets.DOCKER_SERVER_URL }}  
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}  
         
    - name: Push Docker Image to Azure Container Registry 
      run: docker push ${{ secrets.DOCKER_SERVER_URL }}/jobs-widget:${{ steps.gitversion.outputs.fullSemVer }} 
       
    - name: Generate Octopus Deploy build information 
      uses: xo-energy/action-octopus-build-information@v1.1.2
      with: 
        octopus_api_key: ${{ secrets.OCTOPUS_API_KEY }} 
        octopus_server: ${{ secrets.OCTOPUS_SERVER_URL }} 
        octopus_project: jobs-widget 
        output_path: octopus 
        push_package_ids: jobs-widget 
        push_overwrite_mode: OverwriteExisting 
        push_version: ${{ steps.gitversion.outputs.fullSemVer }} 
