name: Build & Test

on:
  push:
    branches:    
      - '**' # matches every branch
    paths: 
          - "**"    
          - "!.octopus/**"      
  workflow_dispatch:      

env:
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
  OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
  OCTOPUS_SPACE: 'Recruit Wizard'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
        
    - name: Display GitVersion config
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
        additionalArguments: "/updateprojectfiles"
        
    - name: Display GitVersion outputs
      run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"
     
    - name: Build the Docker Image 
      working-directory: src
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_SERVER_URL }}/jobs-widget:${{ steps.gitversion.outputs.fullSemVer }} 
       
    - name: Login to Azure Container Registry 
      uses: docker/login-action@v3  
      with: 
        registry: ${{ secrets.DOCKER_SERVER_URL }}  
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}  
         
    - name: Push Docker Image to Azure Container Registry 
      run: docker push ${{ secrets.DOCKER_SERVER_URL }}/jobs-widget:${{ steps.gitversion.outputs.fullSemVer }} 
       
    - name: Push build information to Octopus Deploy 🐙
      uses: OctopusDeploy/push-build-information-action@v3
      with:
        packages: 'jobs-widget'
        version: ${{ steps.gitversion.outputs.fullSemVer }}         
               
    - name: Create a release in Octopus Deploy
      uses: OctopusDeploy/create-release-action@v3
      with:
        project: 'Jobs Widget'
        package_version: ${{ steps.gitversion.outputs.fullSemVer }}
        git_ref: ${{ github.ref }} 
      
